# Generated by Django 2.2.5 on 2020-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_filterling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='filterling',
            field=models.CharField(blank=True, default='전체 페이지', max_length=200),
        ),
    ]
